### PR TITLE
D8/9 - Issues with Contact Element

### PR DESCRIPTION
**Pull request by jitendrapurohit**
Overview
----------------------------------------
Fix issues with contact element.

Before
----------------------------------------

Test webform to replicate all the below cases - https://gist.githubusercontent.com/jitendrapurohit/46a271b38baf1f9b73954e1935c0b734/raw/506088c072c35df154211e45c1392f03fd12a74d/contact_element

1. Description of static contact element not displayed (Element 1 in the attached webform).
2. Search and None prompt not displayed as per values set on the form (Element 2).

image

3. Locked fields are displayed for static contact elements. Replicate it by passing cid3=xx for 3rd contact element. Email is locked (hidden) for the contact but it is still displayed by default.

image

After
----------------------------------------
Fixed.

### CODE REVIEW

**Comment by aaayyuusshh** [comment]
@jitendrapurohit Hey, when I use the file you linked to build a webform, the webform is empty.

**Comment by jitendrapurohit** [comment]
Hi @aaayyuusshh 

Thank you for testing the PRs.

> when I use the file you linked to build a webform, the webform is empty

Not sure how are you using the webform. I just tried to import it on my side and dont see any issues. Below are the steps I followed:

1. Navigate to `/admin/config/development/configuration/single/import?config_type=webform`
2. Paste the content from the above gist.
3. Click on Import button.
4. The webform loads fine and civi elements are loaded as expected.

Can you pls clarify?

Thanks.

**Comment by aaayyuusshh** [comment]
@jitendrapurohit Hey, that worked. I was successfully able to replicate the webform. Thank you!

**Comment by aaayyuusshh** [comment]
@jitendrapurohit @KarinG I was successfully able to curl the .diff link but when trying to apply the .diff file, I get the error shown in the screenshot. ps: curling successfully creates a .diff file in my directory as well, I'm just unable to apply it into my code base. @Aashirbadd tried this as well and he is hit with the same error.
Screen Shot 2021-08-03 at 7 01 56 PM

**Comment by KarinG** [comment]
Hi @aaayyuusshh -> you will need to make sure you’re in the main branch, stash any local edits you may have in the main branch and then pull the latest before you can apply the patch.

git status
(to see what branch you’re on and if you’ve already made edits)

git checkout 8.x-5.x
(to switch to the main branch if needed)

git stash
(to park your local edits)

git pull origin
(to grab the latest code from github)

Then you can curl in the patch and apply it!

**Comment by aaayyuusshh** [comment]
Hey @KarinG , we tried all those steps prior as well and it gives us the same error.

Screen Shot 2021-08-03 at 7 39 19 PM
Screen Shot 2021-08-03 at 7 39 31 PM
Screen Shot 2021-08-03 at 7 40 48 PM

**Comment by aaayyuusshh** [comment]
@KarinG I tried to check if I could curl & apply other PRs and it worked without any errors.

**Comment by KarinG** [comment]
Ok - let me try:

```
karins-MBP:webform_civicrm sysadmin$ git checkout 8.x-5.x
Switched to branch '8.x-5.x'
Your branch is up to date with 'origin/8.x-5.x'.
karins-MBP:webform_civicrm sysadmin$ git stash
No local changes to save
karins-MBP:webform_civicrm sysadmin$ git pull origin
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 5 (delta 4), reused 3 (delta 3), pack-reused 0
Unpacking objects: 100% (5/5), done.
From https://github.com/colemanw/webform_civicrm
   0e86d1e..a98dbc2  8.x-5.x    -> origin/8.x-5.x
Updating 0e86d1e..a98dbc2
Fast-forward
 webform_civicrm.install |  74 +++++++++++++++++++++++++++++++++++++-------------------------------------
 webform_civicrm.module  | 136 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++--------------------------------------------------------------------
 2 files changed, 105 insertions(+), 105 deletions(-)
karins-MBP:webform_civicrm sysadmin$ curl https://patch-diff.githubusercontent.com/raw/colemanw/webform_civicrm/pull/585.diff --output 585.diff
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10059    0 10059    0     0  19998      0 --:--:-- --:--:-- --:--:-- 20037
karins-MBP:webform_civicrm sysadmin$ git apply 585.diff
error: patch failed: tests/src/FunctionalJavascript/WebformCivicrmTestBase.php:304
error: tests/src/FunctionalJavascript/WebformCivicrmTestBase.php: patch does not apply
```

@jitendrapurohit - does this PR need a rebase?

**Comment by KarinG** [comment]
No it does not need a rebase 🤔 

Time to try and 
rm - rf webform_civicrm 
and then git clone the repo again. Perhap we have made some accidental local commits to our locals.

**Comment by aaayyuusshh** [comment]
@KarinG I deleted webform_civicrm & cloned the repo again earlier... and that gave me the error as well.
Just did it again to verify, and I'm still getting the error.

**Comment by KarinG** [comment]
I'm getting that too 🤔

```
karins-MBP:contrib sysadmin$ rm -rf webform_civicrm/
karins-MBP:contrib sysadmin$ git clone https://github.com/colemanw/webform_civicrm.git
Cloning into 'webform_civicrm'...
remote: Enumerating objects: 10312, done.
remote: Counting objects: 100% (853/853), done.
remote: Compressing objects: 100% (417/417), done.
remote: Total 10312 (delta 459), reused 676 (delta 352), pack-reused 9459
Receiving objects: 100% (10312/10312), 3.71 MiB | 492.00 KiB/s, done.
Resolving deltas: 100% (7059/7059), done.
karins-MBP:contrib sysadmin$ cd webform_civicrm
karins-MBP:webform_civicrm sysadmin$ !curl
curl https://patch-diff.githubusercontent.com/raw/colemanw/webform_civicrm/pull/585.diff --output 585.diff
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10059    0 10059    0     0  18456      0 --:--:-- --:--:-- --:--:-- 18423
karins-MBP:webform_civicrm sysadmin$ git apply 585.diff
error: patch failed: tests/src/FunctionalJavascript/WebformCivicrmTestBase.php:304
error: tests/src/FunctionalJavascript/WebformCivicrmTestBase.php: patch does not apply
```

Ok let's have a look -> ok this does work:

```
karins-MBP:webform_civicrm sysadmin$ cat 585.diff |patch -p1 --dry-run
patching file js/webform_civicrm_contact.js
patching file js/webform_civicrm_forms.js
Hunk #1 succeeded at 87 (offset 2 lines).
patching file src/Plugin/WebformElement/CivicrmContact.php
patching file templates/webform-civicrm-contact.html.twig
patching file tests/src/FunctionalJavascript/ExistingContactElementTest.php
Hunk #2 succeeded at 106 (offset 4 lines).
Hunk #3 succeeded at 157 (offset 15 lines).
patching file tests/src/FunctionalJavascript/WebformCivicrmTestBase.php
Hunk #1 succeeded at 318 with fuzz 2 (offset 14 lines).
Hunk #2 succeeded at 393 (offset 24 lines).
patching file webform_civicrm.module
karins-MBP:webform_civicrm sysadmin$ 
```

So you then do this without the --dry-run:
`cat 585.diff |patch -p1`

That patched 7 files - which looks right 🎉

I'm not sure why `git apply` did not work in this case. But plan B seems to work.

**Comment by aaayyuusshh** [comment]
@KarinG Tried that and it gives no errors in the terminal and I get the same output as yours above. However, the changes made by the PR were not updated in my respective local files after this command.

**Comment by jitendrapurohit** [comment]
I've just done a rebase and pushed a fake commit to update the lines in `tests/src/FunctionalJavascript/WebformCivicrmTestBase.php` file so it matches the latest codebase. Can you pls retry? @aaayyuusshh 

Thanks.

**Comment by aaayyuusshh** [comment]
@jitendrapurohit Yup, git apply works now. Thank you for sticking through.

**Comment by aaayyuusshh** [comment]
@KarinG  @jitendrapurohit I successfully reproduced the issue and upon curling the PR and clearing all caches I noticed the following:

**Working:**
- Description of static contact element is displayed in the webform.
Screen Shot 2021-08-04 at 11 34 40 AM

- Not Found Prompt is displayed in the webform when it cannot find an existing contact thats been typed.
Screen Shot 2021-08-04 at 11 26 57 AM

- Locked field email is not displayed when you load the webform by passing cid3 for Element 3 (might be a problem associated with it, look below)
Screen Shot 2021-08-04 at 11 35 55 AM


**Problem?? :**
- Search Prompt is only displayed when you first load the webform and click the box under "Autocomplete Existing Contact"
             -  If you click outside the box, and click in the box again, it will not display the Search Prompt (will display if you 
                 reload the page and click the box again though)
Screen Shot 2021-08-04 at 11 38 40 AM
Screen Shot 2021-08-04 at 11 38 13 AM


- When loading a webform by passing cid3, the page will briefly show the email field  for a split second and it will disappear.

**Comment by aaayyuusshh** [comment]
@jitendrapurohit Hey, just following up on this. Any updates?

**Comment by KarinG** [comment]
Hi @jitendrapurohit - I've rebased this (small conflict since I merged the token PR) and am running the tests again.

**Comment by KarinG** [comment]
Sorry this needs a bit more work re: the test side of things (again b/c of the token PR that I merged):

```
PHP Fatal error:  Cannot redeclare Drupal\Tests\webform_civicrm\FunctionalJavascript\WebformCivicrmTestBase::fillCKEditor() in /home/runner/work/webform_civicrm/webform_civicrm/tests/src/FunctionalJavascript/WebformCivicrmTestBase.php on line 512
Error: Process completed with exit code 255.
```

**Comment by jitendrapurohit** [comment]
yes, that duplicate function seems to have already merged in token PR. Have fixed this and updated the change. The build is passing now.

>- If you click outside the box, and click in the box again, it will not display the Search Prompt (will display if you

Hmm, that's because the input search text inside the autocomplete is limited to 46px (done by core drupal). If you click on this part, the search text will be shown on every click.

image

It behaved in the same way in d7 so don't think we need to fix anything here. Let me know if any objections @KarinG @aaayyuusshh

**Comment by KarinG** [comment]
No objections! 🎉

**Pull request merged**
