### PR TITLE
Fetch fields with api instead of sql query

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Replaces a whopping sql query with an api call.

Before
----------------------------------------
SQL :(

After
----------------------------------------
API :)

### CODE REVIEW

**Comment by colemanw** [comment]
@kainuk wanna crack at porting this to the 8.x branch?

**Comment by kainuk** [comment]
@colemanw I will put it on my list

**Comment by KarinG** [comment]
Part of my custom fields testing this morning. I made some more custom fields of different HTML types - everything works fine. See https://github.com/colemanw/webform_civicrm/pull/260 - for more details on testing

**Comment by KarinG** [comment]
Thanks @coleman !

**Comment by colemanw** [comment]
@kainuk this has been merged to 7.x but still needs to be ported to 8.x.

**Comment by colemanw** [comment]
@KarinG porting this to 8.x is going to be critical soon, as the custom data schema is changing per https://github.com/civicrm/civicrm-core/pull/16992 - the APIv3 provides a compatibility layer to make the schema change unnoticeable, but the direct query will stop working. I haven't heard any progress from @kainuk in porting this.

**Pull request merged**
