### PR TITLE
Event registrations

### PR DESCRIPTION
**Pull request by mglaman**
Overview
----------------------------------------
Ensures event registrations work via Webform submission.

Comments
----------------------------------------
Currently, event registrations are populated.

### CODE REVIEW

**Comment by dsnopek** [comment]
Seems to just work in my simple test! No comments on the code, that all looks straightforward. Let's do this so we can get on to some more complicated configuration!

**Comment by KarinG** [comment]
Merci!

**Comment by KarinG** [comment]
It says it's Draft - so I can't merge this as is.

**Comment by mglaman** [comment]
Moved out of draft :) Apologies, since the feature rolled out I have become a creature of habit to use it.

**Comment by KarinG** [comment]
All good! :-)

**Pull request merged**
