### PR TITLE
D8/9 - Allow number field to be retyped into options

### PR DESCRIPTION
**Pull request by jitendrapurohit**
Overview
----------------------------------------
Allow number fields to be retyped into options element.

Before
----------------------------------------
Number fields (eg Contribution Amount, etc) cannot be changed to select, radio, checkboxes, etc.

After
----------------------------------------
Can be retyped into different widgets.

image

Select `CiviCRM Options` from the list of related types.

image

If you still wanna change the type to native select, radio, radio_other, select_other, change the type from CiviCRM Options => these types.

image
 

Technical Details
----------------------------------------
This PR adds a new plugin for numeric elements. (Civicrm Number). This can be retyped into our custom plugin Civicrm Options which is already able to render as select, radio, etc based on configurable settings for Listbox, Multiple checkboxes.

Comments
----------------------------------------
@KarinG

### CODE REVIEW

**Comment by KarinG** [comment]
Ok testing this on one of our Sponsor's sites:

✅ Using UI to change from CiviCRM Number to CiviCRM Options

image

**Then configuring Options:**
image

✅ Options look good and participant_fee is passed on properly to CiviCRM

I am seeing a couple of notices:

image

If when in the UI:
image

I hit (-) on the second option -> the UI for the select options disappear:
image

I'll reproduce this on one of our own testing sites to looks for more clues as to what triggers the notices.

**Comment by mpaulso** [comment]
I tried testing, but created an event.
Was able to change event fees from a CiviCRM Number to CiviCRM Options, radio buttons

But when checking out, received the following errors

image

image


```
YAML
contact_pagebreak:
  '#type': wizard_page
  '#form_key': contact_pagebreak
  '#title': 'Contact Information'
  civicrm_1_contact_1_fieldset_fieldset:
    '#type': fieldset
    '#title': 'Contact 1'
    '#form_key': civicrm_1_contact_1_fieldset_fieldset
    '#parent': contact_pagebreak
    civicrm_1_contact_1_contact_existing:
      '#type': civicrm_contact
      '#search_prompt': '- Choose existing -'
      '#widget': hidden
      '#form_key': civicrm_1_contact_1_contact_existing
      '#allow_create': 1
      '#none_prompt': '+ Create new +'
      '#default': user
      '#contact_type': individual
      '#parent': civicrm_1_contact_1_fieldset_fieldset
      '#extra': {  }
      '#title': 'Existing Contact'
    civicrm_1_contact_1_contact_first_name:
      '#type': textfield
      '#contact_type': individual
      '#form_key': civicrm_1_contact_1_contact_first_name
      '#extra':
        width: 20
      '#parent': civicrm_1_contact_1_fieldset_fieldset
      '#title': 'First Name'
    civicrm_1_contact_1_contact_last_name:
      '#type': textfield
      '#contact_type': individual
      '#form_key': civicrm_1_contact_1_contact_last_name
      '#extra':
        width: 20
      '#parent': civicrm_1_contact_1_fieldset_fieldset
      '#title': 'Last Name'
    civicrm_1_contact_1_email_email:
      '#type': email
      '#form_key': civicrm_1_contact_1_email_email
      '#extra':
        width: 20
      '#parent': civicrm_1_contact_1_fieldset_fieldset
      '#title': Email
    civicrm_1_participant_1_participant_fee_amount:
      '#type': civicrm_options
      '#title': 'Participant Fee'
      '#options':
        5: 'Beginner -$5'
        10: Intermediate-$10
        15: 'Advanced- $15'
      '#data_type': 0
      '#form_key': civicrm_1_participant_1_participant_fee_amount
      '#parent': civicrm_1_contact_1_fieldset_fieldset
  civicrm_2_contact_1_fieldset_fieldset:
    '#type': fieldset
    '#title': 'Contact 2'
    '#form_key': civicrm_2_contact_1_fieldset_fieldset
    '#parent': contact_pagebreak
    civicrm_2_contact_1_contact_first_name:
      '#type': textfield
      '#contact_type': individual
      '#form_key': civicrm_2_contact_1_contact_first_name
      '#extra':
        width: 20
      '#parent': civicrm_2_contact_1_fieldset_fieldset
      '#title': 'First Name'
    civicrm_2_contact_1_contact_last_name:
      '#type': textfield
      '#contact_type': individual
      '#form_key': civicrm_2_contact_1_contact_last_name
      '#extra':
        width: 20
      '#parent': civicrm_2_contact_1_fieldset_fieldset
      '#title': 'Last Name'
    civicrm_2_contact_1_email_email:
      '#type': email
      '#form_key': civicrm_2_contact_1_email_email
      '#extra':
        width: 20
      '#parent': civicrm_2_contact_1_fieldset_fieldset
      '#title': Email
    civicrm_2_participant_1_participant_fee_amount:
      '#type': civicrm_options
      '#title': 'Participant Fee'
      '#options':
        5: 'Beginner -$5'
        10: Intermediate-$10
        15: 'Advanced- $15'
      '#data_type': 0
      '#form_key': civicrm_2_participant_1_participant_fee_amount
      '#parent': civicrm_2_contact_1_fieldset_fieldset
contribution_pagebreak:
  '#type': wizard_page
  '#form_key': contribution_pagebreak
  '#title': Payment
  civicrm_1_billing_1_number_of_billing_1_fieldset_fieldset:
    '#type': fieldset
    '#title': 'Billing Address'
    '#form_key': civicrm_1_billing_1_number_of_billing_1_fieldset_fieldset
    '#parent': contribution_pagebreak
    civicrm_1_contribution_1_contribution_billing_address_first_name:
      '#type': textfield
      '#extra':
        width: 60
      '#set': billing_1_number_of_billing
      '#parent': civicrm_1_billing_1_number_of_billing_1_fieldset_fieldset
      '#form_key': civicrm_1_contribution_1_contribution_billing_address_first_name
      '#title': 'Billing First Name'
    civicrm_1_contribution_1_contribution_billing_address_last_name:
      '#type': textfield
      '#extra':
        width: 60
      '#set': billing_1_number_of_billing
      '#parent': civicrm_1_billing_1_number_of_billing_1_fieldset_fieldset
      '#form_key': civicrm_1_contribution_1_contribution_billing_address_last_name
      '#title': 'Billing Last Name'
    civicrm_1_contribution_1_contribution_billing_address_street_address:
      '#type': textfield
      '#extra':
        width: 60
      '#set': billing_1_number_of_billing
      '#parent': civicrm_1_billing_1_number_of_billing_1_fieldset_fieldset
      '#form_key': civicrm_1_contribution_1_contribution_billing_address_street_address
      '#title': 'Street Address'
    civicrm_1_contribution_1_contribution_billing_address_postal_code:
      '#type': textfield
      '#extra':
        width: 7
      '#set': billing_1_number_of_billing
      '#parent': civicrm_1_billing_1_number_of_billing_1_fieldset_fieldset
      '#form_key': civicrm_1_contribution_1_contribution_billing_address_postal_code
      '#title': 'Postal Code'
    civicrm_1_contribution_1_contribution_billing_address_city:
      '#type': textfield
      '#extra':
        width: 20
      '#set': billing_1_number_of_billing
      '#parent': civicrm_1_billing_1_number_of_billing_1_fieldset_fieldset
      '#form_key': civicrm_1_contribution_1_contribution_billing_address_city
      '#title': City
    civicrm_1_contribution_1_contribution_billing_address_country_id:
      '#type': civicrm_options
      '#extra':
        aslist: 1
        items: |-
[very long list of countries 🙂]
      '#title': Country
      '#civicrm_live_options': 1
    civicrm_1_contribution_1_contribution_billing_address_state_province_id:
      '#type': textfield
      '#extra':
        maxlength: 5
        width: 4
      '#data_type': state_province_abbr
      '#set': billing_1_number_of_billing
      '#parent': civicrm_1_billing_1_number_of_billing_1_fieldset_fieldset
      '#form_key': civicrm_1_contribution_1_contribution_billing_address_state_province_id
      '#title': State/Province
```

**Comment by KarinG** [comment]
@jitendrapurohit -> if (on Mel's form) I go from CiviCRM Options back to CiviCRM Number -> and then try to submit the webform I get 'Illegal Choice' -> the YAML after changing back looks like (note: #data_type + `#options` leftovers):

```
    civicrm_2_participant_1_participant_fee_amount:
      '#type': civicrm_number
      '#title': 'Participant Fee'
      '#options':
        5: 'Beginner -$5'
        10: Intermediate-$10
        15: 'Advanced- $15'
      '#data_type': 0
      '#form_key': civicrm_2_participant_1_participant_fee_amount
      '#parent': civicrm_2_contact_1_fieldset_fieldset
```

**Comment by KarinG** [comment]
For reference an out of the box participant_fee -> 

```
    civicrm_1_participant_1_participant_fee_amount:
      '#type': civicrm_number
      '#data_type': Money
      '#extra':
        field_prefix: $
        point: .
        separator: ','
        decimals: 2
        min: 0
      '#form_key': civicrm_1_participant_1_participant_fee_amount
      '#parent': civicrm_1_contact_1_fieldset_fieldset
      '#title': 'Participant Fee'
```

**Comment by KarinG** [comment]
So even with native participant fee amount fields we get the same error -> Contribution + Event Registration is completed -> but -> not Results recorded in webform as it chokes on something before it gets to that stage. 

image

**Comment by KarinG** [comment]
Note: I can even see the activities -> not sure yet what it's choking on.

image

**Comment by jitendrapurohit** [comment]
>I hit (-) on the second option -> the UI for the select options disappear:
>@jitendrapurohit -> if (on Mel's form) I go from CiviCRM Options back to CiviCRM Number -> and then try to submit the webform I get 'Illegal Choice' -> the YAML after changing back looks like (note: #data_type + #options leftovers):

@KarinG I was able to replicate these issues and have fixed it in the latest commit. I wasn't able to replicate @mpaulso error re participant fee.

> So even with native participant fee amount fields we get the same error

Does that mean it replicates without this PR as well? If yes, can we handle it in a separate PR?

**Comment by KarinG** [comment]
Interesting (and unexpected) test failure. Going to re-run the jobs to double check that this is real:

```
1) Drupal\Tests\webform_civicrm\FunctionalJavascript\ExistingContactElementTest::testRenderingOfExistingContactElement
Behat\Mink\Exception\ResponseTextException: The text "Description of the static contact element" was not found anywhere in the text of the current page.
```

**Comment by KarinG** [comment]
@jitendrapurohit -> re-run of jobs shows the test failure is real.

```
There was 1 error:

1) Drupal\Tests\webform_civicrm\FunctionalJavascript\ExistingContactElementTest::testRenderingOfExistingContactElement
Behat\Mink\Exception\ResponseTextException: The text "Description of the static contact element" was not found anywhere in the text of the current page.
```

and

```
There was 1 failure:

1) Drupal\Tests\webform_civicrm\FunctionalJavascript\ExistingContactElementTest::testTokensInEmail
Failed asserting that 'Submitted on Sun, 12/12/2021 - 02:13\n
\n
Submitted by: admin\n
\n
Submitted values are:\n
\n
-------- Contact 1 \n
-----------------------------------------------------------\n
\n
*Existing Contact*\n
Frederick Pabst\n
*First Name*\n
Frederick\n
*Last Name*\n
Pabst\n
*Email*\n
frederick@pabst.io [1]\n
\n
[1] mailto:frederick@pabst.io\n
' contains "Existing Contact - Frederick Pabst.".
```

**Comment by KarinG** [comment]
Re: participant fee -> we're trying to reproduce that isolated from the PR now. This PR will just be tested with Contribution Amount.

**Comment by KarinG** [comment]
Ok this completely unrelated PR -> failed tests with the same error on merge: 
image

**Comment by KarinG** [comment]
Ok pushing a trivial commit to get the tests to re-run

**Comment by KarinG** [comment]
Awesome - this now passes 🎉

**Comment by KarinG** [comment]
Existing automated tests ✅
Manual testing ✅
Live site confirmation ✅

**Comment by KarinG** [comment]
Screenshot:

image

**Comment by KarinG** [comment]
image

**Pull request merged**
