### PR TITLE
No auto fill custom data

### PR DESCRIPTION
**Pull request by vakeesan26**
https://www.drupal.org/project/webform_civicrm/issues/2955665

### CODE REVIEW

**Comment by colemanw** [comment]
Can you please list the steps to reproduce this bug?

**Comment by vakeesan26** [comment]
In existing contact field setting we have a setting called "Skip auto filling of"
In this setting i have chosen only one custom field group.
so when i view the webform i expected those custom group fields as empty.
but it is not working as [expected.]
[in the setting if i choose all custom groups then when i view the webform all custom fields were empty]

[ Auto Fill ](https://www.drupal.org/files/issues/2018-03-28/auto_fill.JPG)

**Comment by ssngbala** [comment]
can you please merge this patch ?

**Comment by colemanw** [comment]
@ssngbala if you have reviewed and tested this patch, please describe how you reproduced the bug and your results before/after this patch.

**Comment by vakeesan26** [comment]
$this->getCustomData($cid); loading all the custom data regardless $exclude setting.

**Comment by colemanw** [comment]
I checked this over and determined that using `array_filter()` would be more efficient than calling the `getCustomData` function repeatedly. Fixed via 2e0d2b9

**Pull request closed without merging**
