### PR TITLE
Address display of tags

### PR DESCRIPTION
**Pull request by demeritcowboy**
Overview
----------------------------------------
This should address the test fail but I'm not sure yet what api3 will return for `return` => `tag` lower down. Let's find out.

### CODE REVIEW

**Comment by petednz** [comment]
I clicked the link to see what failings were happening with Addresses - lol.

**Comment by demeritcowboy** [comment]
Ha made you look.

But good point I should update the title.

**Comment by KarinG** [comment]
😂 Dave is looking at Major Donor now being Major_Donor in dev-master. Investing in automated tests has been the best thing ever.

**Comment by demeritcowboy** [comment]
It's currently failing because `civicrm_api3('contact', 'get', 'return' => ['tag'])` will return the `name` for the tag. I'm going to argue that this is "correct", simply because there's no robust way to get from label to name if instead it returned label, but you can always get from name to label. In the context of this test, it's using it for comparison/validation, so name is appropriate. I can see an argument that some people might be using such a call for display purposes and so now that same call will display the internal name, but it has to be one or the other, so it's going to be "wrong" for half of the people either way.

**Comment by KarinG** [comment]
Funny the branch is major-donor (perhaps another variation we need to account for) :-)

**Comment by KarinG** [comment]
@jitendrapurohit - I've reviewed and tested. Since it's not trivial - could you please have a look this weekend as well? If you concur - then go ahead and hit the Merge button!

**Comment by jitendrapurohit** [comment]
ah, maybe we missed the tagset. Follow up PR - https://github.com/colemanw/webform_civicrm/pull/921

**Pull request merged**
