### PR TITLE
Fix tokens to be displayed on webforms

### PR DESCRIPTION
**Pull request by jitendrapurohit**
Overview
----------------------------------------
Tokens not rendered correctly on webforms.

Before
----------------------------------------

image

After
----------------------------------------
image

Comments
----------------------------------------
https://www.drupal.org/project/webform_civicrm/issues/3052874

### CODE REVIEW

**Comment by KarinG** [comment]
Hi @jitendrapurohit - thank you for this. I've asked @jackrabbithanna to review/test this PR.

**Comment by KarinG** [comment]
Actually I think this has already been addressed in: https://github.com/colemanw/webform_civicrm/pull/207/files

**Comment by jitendrapurohit** [comment]
Ah yes. haven't looked at it. Thanks @KarinG. closing.

**Comment by KarinG** [comment]
No worries - I only just had a chance to look at it myself this morning.

**Pull request closed without merging**
