### PR TITLE
D7: make Contact selectable for Contributions

### PR DESCRIPTION
**Pull request by sluc23**
Overview
----------------------------------------
In `webform_civicrm` when creating a Contribution, it's assigned to **Contact 1** by default.  
There are some use cases where we need to create several Contacts in the same webform or having conditional contacts creation (Individual or Organization in the same webform selectable by the user, for instance) and we don't want to assign the new Contribution (one off and/or recurring) to **Contact 1**.

This PR adds the possibility to select to which contact the contribution will be assigned, or selectable by the User as well, that could be manual assigned, or use in different scenarios (using webform_conditional to assing the contribution to Contact X depending on criteria)  

webform_civicrm

D7 or D8?
----------------------------------------
Drupal 7

Before
----------------------------------------
The Contribution is always assigned to **Contact 1**

After
----------------------------------------
The Contribution can be assigned to any Contact available in the webform, even *selectable by user*, adding more webforms' use cases 

Technical Details
----------------------------------------
This PR adds `contribution_contact_id` field as part of the Contribution fields

Comments
----------------------------------------
I'm adding this to `7.x-5.x` branch because it's the version we are still using in Drupal 7. I won't be ready to port this to Drupal 8 at the moment

### CODE REVIEW

**Comment by sluc23** [comment]
@colemanw @KarinG I'm submitting this PR, to check if it would be an interesting addition to current `webform_civicrm` behaviour and has no conflicts with the original purpose of the module. Still some testing needed, but if you think this can be merged, I'll move it forwards. tx

**Comment by KarinG** [comment]
I do like solutions/PRs that make webform civicrm module even more flexible 👍 

Every PR these days will need a D8 port - but we can help with that.

**Comment by sluc23** [comment]
@KarinG @colemanw we have tested this patch and it works fine for Drupal 7. It's not [WIP] anymore.

**Comment by KarinG** [comment]
Hi @sluc23 - we really need this in a D8/D9 PR first. For the D8/D9 branch we now have automated Github Actions for testing including Contributions and multiple Line Items. I'm happy to keep this PR open until you have a chance to do that. Alternatively, if ixiam would like to become a sponsor of webform civicrm module (DM me on Mattermost if you're interested) then either Jitendra or myself can take this PR to D8/D9 for you. As I mentioned previously I generally do like the idea here.

**Comment by sluc23** [comment]
@KarinG , yes I know the D8/D9 policy that is in place now. I've just updated this PR because we found an issue, just to keep it updated and fixed, not expecting to be merged in D7. Sadly, as I said before, we are not surfing the D8/9 wave yet, and it will take us time to get there. That's why we decided to use our own fork for `7.x` [here](https://github.com/ixiam/webform_civicrm).

You can close all the PRs we made for D7 if they are confusing and mislead into thinking they will be merged soon, no worries.

**Comment by KarinG** [comment]
I'm happy to keep it on the books. And thank you for updating the PR. Please note that (of course) any bugs/maintenance can still go into D7. 

If you need help getting started with D8/D9 do touch base in Drupal channel on Mattermost. Many folks out there who will be happy to help.

**Comment by francescbassas** [comment]
@sluc23 is this solution stable?

@KarinG are there any plans to push this PR forward?

We have two donation forms (on D7 instances) differentiated by organizations and by individuals that could be unified into one with this functionality (with the consequent simplification in maintenance).

**Comment by KarinG** [comment]
@francescbassas - it's D8/D9 + automated test first for new functionality and even then we need to be cautious back porting to D7.

**Comment by KarinG** [comment]
Other reasons to update 🙂 -> checkout the new Billing Fields in D8/D9:

image

**Comment by francescbassas** [comment]
Thanks @KarinG. I would love to update to D8/D9 but for now I am running out of time and resources to update websites and CRM from the 5 instances I manage 😅

**Pull request closed without merging**
