### PR TITLE
Use api to retrieve relationship data

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Another sql -> api swapout

Before
----------------------------------------
SQL :(

After
----------------------------------------
API :)

Technical Details
----------------------------------------
Since the api automatically fetches custom data, I was able to remove some extra code that did that separately.

### CODE REVIEW

**Comment by colemanw** [comment]
To test this PR, expose some relationships to the form, including custom relationship fields. They should load and save correctly before/after the patch.

**Comment by KarinG** [comment]
@kainuk - are you able to port this one to D8 as well? Then I’ll review both in one go.

**Comment by colemanw** [comment]
@KarinG already done: #252

**Comment by KarinG** [comment]
Doh - ok will test this :-)

**Comment by KarinG** [comment]
Testing -> https://github.com/colemanw/webform_civicrm/pull/252

**Pull request merged**
