### PR TITLE
Use attachment api instead of internal functions

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Use the attachment api to future-proof file handling.

Before
----------------------------------------
More code, less stable.

After
----------------------------------------
Less code, more stable.

### CODE REVIEW

**Comment by colemanw** [comment]
To test this PR, add a custom field of type "file" for an existing contact. It should save files and then show the existing file when reloading the webform. Behavior should be unchanged before/after this PR.

**Comment by KarinG** [comment]
ok - tested: I can upload a File via the Webform -> and I can view it in CiviCRM! Merging this. 

PS - Going back to the webform -> there is no indication/flag that I've already just uploaded a File -> so I can (accidentally) overwrite it.

**Comment by KarinG** [comment]
And another one done! How many are left?

**Comment by colemanw** [comment]
Nice. #251 should be fairly simple to review...

**Pull request merged**
