### PR TITLE
New contact not attached to contact reference custom field

### PR DESCRIPTION
**Pull request by pradpnayak**
Overview
----------------------------------------
Contact reference custom field not saved for new creation

Steps to replicate:

1. Create custom field of type contact reference
2. include it in a webform

### CODE REVIEW

**Comment by KarinG** [comment]
Hi Pradeep -> you'll want to PR against the 6.x branch [8.x-5.x is no longer supported].

**Comment by pradpnayak** [comment]
Hi @KarinG 

Have changed the branch.

Thanks
Pradeep

**Comment by KarinG** [comment]
Can you please force push to kick off the tests?

**Comment by KarinG** [comment]
Ah you may need to close this PR and open a new one against 6.x to kick off our test matrix?

**Comment by pradpnayak** [comment]
closing in favor of https://github.com/colemanw/webform_civicrm/pull/798

**Pull request closed without merging**
