### PR TITLE
Changed "Additional Options" tab into "Additional Settings"

### PR DESCRIPTION
**Pull request by Aashirbadd**
Overview
----------------------------------------
In the webform CiviCRM settings form, the tab named "Additional Options" was renamed to "Additional Settings" as required to resolve an issue in the Webform CiviCRM issue queue assigned to me.

Link of the issue: 
https://www.drupal.org/project/webform_civicrm/issues/3223112 

Before
----------------------------------------
The bottom most tab in the CiviCRM settings form that allows admin users to access additional settings for the webform is named "Additional Options".
image

After
----------------------------------------
The bottom most tab in the CiviCRM settings form has now been renamed to "Additional Settings" to make it more clear to the admin user what features that tab provides.
Screen Shot 2021-07-10 at 11 07 39 AM

Technical Details
----------------------------------------
This fix involved a simple label change in the AdminForm.php file in the source folder for this project. Where the title of the bottom most tab was renamed from "Additional Options" to "Additional Settings".

Comments
----------------------------------------
_Anything else you would like the reviewer to note_

### CODE REVIEW

**Comment by KarinG** [comment]
@Aashirbadd - I’ve approved you as a first time contributor so that will now kick off a series of automated tests!

**Comment by KarinG** [comment]
@Aashirbadd - the automated tests fail because we have two tests that go into this section to test functionality. The tests are trying to click 'Additional Options' -> but that no longer exists. So we need two more small edits (to these two tests) to be able to merge this PR. If you push these to your Github repo then it will automatically update this PR an re-run the tests.

This is the test output -> 

tests/src/FunctionalJavascript/ContactSubmissionTest.php:141
tests/src/FunctionalJavascript/ContributionDummyTest.php:58

```
1) Drupal\Tests\webform_civicrm\FunctionalJavascript\ContactSubmissionTest::testStaticAndAutocompleteOnContactElement
Behat\Mink\Exception\ElementNotFoundException: Link with id|title|alt|text "Additional Options" not found.

/home/runner/drupal/vendor/behat/mink/src/Element/TraversableElement.php:70
/home/runner/work/webform_civicrm/**webform_civicrm/tests/src/FunctionalJavascript/ContactSubmissionTest.php:141**

2) Drupal\Tests\webform_civicrm\FunctionalJavascript\ContributionDummyTest::testOnePageDonation
Behat\Mink\Exception\ElementNotFoundException: Link with id|title|alt|text "Additional Options" not found.

/home/runner/drupal/vendor/behat/mink/src/Element/TraversableElement.php:70
/home/runner/work/webform_civicrm/**webform_civicrm/tests/src/FunctionalJavascript/ContributionDummyTest.php:58** 
```

**Comment by Aashirbadd** [comment]
@KarinG - Hey Karin, I have made the changes to the required tests, and renamed the "Additional Options" fields to "Additional Settings".

**Comment by KarinG** [comment]
And now the tests are all ✅ - I'm going to squash the commits and merge this 🎉

**Comment by colemanw** [comment]
@Aashirbadd you mentioned an issue in the description but didn't link to it. It's best to add a link so we can find it.

**Comment by Aashirbadd** [comment]
@colemanw Thanks for letting me know! I have updated the original commit message so the link to the assigned issue is in it  too.

**Comment by colemanw** [comment]
> I have updated the original commit message so the link to the assigned issue is in it too.

That's not possible. This PR was merged 9 days ago. Commits cannot be updated once merged to the main branch.

Update: Oh I see, you meant the PR description, not the commit message.

**Pull request merged**
