### PR TITLE
Support larger number of max_instances for activities.

### PR DESCRIPTION
**Pull request by KarinG**
Supporting larger number of max_instances of activities for larger projects.

### CODE REVIEW

**Comment by colemanw** [comment]
Looks good.

**Comment by KarinG** [comment]
Thanks. It's on a live site happily creating up to 35 activities with one form submission.

**Comment by colemanw** [comment]
Could be bumped up to 50 even. In theory these fields could be unlimited but in practice we tend to hit up against PHP's max allowed POST size when forms get too massive which is why I think reasonable limits are a good thing.

**Comment by KarinG** [comment]
Absolutely.

**Comment by KarinG** [comment]
required max_input_vars to be bumped up quite a bit :-)

**Pull request merged**
