### PR TITLE
Fix Address fields not being updated

### PR DESCRIPTION
**Pull request by omarabuhussein**
fixing the issue reported here https://github.com/colemanw/webform_civicrm/pull/24#issuecomment-216327009  that address fields (city, country , street address ... etc)  don't get updated after submitting the form.

### CODE REVIEW

**Comment by nishant-bhorodia** [comment]
Hello @omarabuhussein, @colemanw ,

Code looks good to me. This handles address fields as well as supplemental address too !!
It would be great if @mercurymotos could have a look at this as well.

Many Thanks!

**Comment by colemanw** [comment]
I'll merge this based on your feedback @nishant-bhorodia.
@mercurymotos if you get a chance to test this out that would be helpful too.

**Comment by omarabuhussein** [comment]
@colemanw 

one of our QA team at @compucorp tested it and it works .. to give you a little background on how we use civicrm_webform module , we have this form :

selection_025

where we allow users to edit their data from it , and on this form we tested the patch.

**Comment by omarabuhussein** [comment]
hoooo we submitted our comments nearly at the same time :smile:  , thanks @colemanw

**Comment by omarabuhussein** [comment]
@colemanw  

a quick question ... when are you expecting to release the next stable version ?  .. ( 7.x-4.15 ) is latest one which is released  at ( Feb 19 ) [ which is so long ago ].

**Comment by colemanw** [comment]
@omarabuhussein thanks for the testing. I've just published a new release :)

**Comment by omarabuhussein** [comment]
oh ,, cool :D

**Comment by mercurymotos** [comment]
And I’ve finally shaken off enough of the summer to test as well - it works as expected!  thanks so much.

**Pull request merged**
