### PR TITLE
Add missing bracket.

### PR DESCRIPTION
**Pull request by puresyntax71**
Related to the fix on #753. There was a missing bracket which led to the error:

> Uncaught Error: Syntax error, unrecognized expression: [name*="civicrm_2_contact_1_address_"

### CODE REVIEW

**Comment by KarinG** [comment]
Thank you!

**Comment by MegaphoneJon** [comment]
This seems identical to #903, I wonder how they were both mergeable?

**Comment by KarinG** [comment]
I knew I had seen this recently. Looking...

**Comment by KarinG** [comment]
And your commit is still the latest -> very odd how Github didn't flag this PR. Essentially we just merged nothing.

image

**Pull request merged**
