### PR TITLE
Update Github Testing Matrix

### PR DESCRIPTION
**Pull request by demeritcowboy**
Overview
----------------------------------------
Use 9.1 with latest numbered release and 9.2 with latest release-candidate.

For clarity since composer's method of specifying version is difficult:

`~9.1.1` means the latest 9.1 - the last digit will auto-adjust to whatever the latest is. Before when it said `^9.1`, it will install 9.2.x.

### CODE REVIEW

**Comment by demeritcowboy** [comment]
@KarinG  for master use `dev-master`

**Comment by KarinG** [comment]
Ah ok! On it.

-- 
Karin G.M. Gerritsen, Ph.D.
Semper Information Technology Inc.
Interactive Drupal/CiviCRM websites
Web: http://www.semper-it.com
Twitter: @KarinSemperIT

Schedule a meeting: https://calendly.com/karing-semperit

**Comment by KarinG** [comment]
Filed issue -> https://lab.civicrm.org/dev/financial/-/issues/180

**Comment by KarinG** [comment]
Capturing this -> 
image

Now re-running against dev-master!

**Comment by KarinG** [comment]
Re-running against - dev-master

**Comment by seamuslee001** [comment]
@KarinG the RC is 5.41 not 5.39 which is the ESR

**Comment by KarinG** [comment]
Ok finalized the versions.

**Pull request merged**
