### PR TITLE
Handle Activity/Case tags

### PR DESCRIPTION
**Pull request by colemanw**
This is an untested port of #268

### CODE REVIEW

**Comment by colemanw** [comment]
Anyone using D8 webform and able to test this out?

**Comment by KarinG** [comment]
I'm using D8 webform :-) but I've never used Case with it (not even in D7), so not sure what I what I would need to check/keep an eye etc.

**Comment by colemanw** [comment]
@KarinG this adds support for both activity and case tags. Since the code is the same for both I think it's fine to just test one of them (esp since this patch was already accepted for the 7.x branch). Try this:

- Create a couple tags for activities
- Create a webform and expose the activity tag fields
- Try tagging and untagging activities via webform

**Comment by KarinG** [comment]
Ok I've tested Create a webform and expose the activity tag fields and am able to Tag activities via webform. I've not tried untagging as I'd be surprised it we could load existing Activities at this point, but that's ok. Merging this!

**Pull request merged**
