### PR TITLE
Only perform validation on state/province field when it is set

### PR DESCRIPTION
**Pull request by JKingsnorth**
See https://www.drupal.org/project/webform_civicrm/issues/3219316

### CODE REVIEW

**Comment by KarinG** [comment]
Port of https://github.com/colemanw/webform_civicrm/pull/567

**Comment by KarinG** [comment]
Removed port as this is not a backport of a D8 PR that is merged.

**Comment by jitendrapurohit** [comment]
Hi @JKingsnorth 

Just tried to replicate this on d7 using the steps from https://www.drupal.org/project/webform_civicrm/issues/3219316

Before the PR -

image

After applying the PR, it still returns the same error. As I think the change here does an empty check but on hiding the address fields, the state value still has the victoria selected in my case. 

Am i missing anything? [Here's](https://gist.githubusercontent.com/jitendrapurohit/16833b438029341995393f5b035d4cf1/raw/651bcce354ff64be5c4c3c4f3857cc1b2c7b3804/state_select_error.txt) the exported form if that helps.

**Comment by jitendrapurohit** [comment]
Ah, probably some caching issue. Yes, I can confirm it works fine and submits the webform without any issue 👍

**Comment by JKingsnorth** [comment]
Great, thanks @jitendrapurohit -  do you think this can be merged now @KarinG ?

**Comment by KarinG** [comment]
@JKingsnorth - I'll check in with Jitendra this weekend to finalize this!

**Comment by jitendrapurohit** [comment]
It seems to be doing what was already being done at eg https://github.com/colemanw/webform_civicrm/blob/7.x-5.x/includes/wf_crm_webform_postprocess.inc#L329, i.e, we were already validating the state value when filled. It is just another variable checked in this PR. Looks fine to me. Merging.

**Pull request merged**
