### PR TITLE
Adding test for ACHEFT - status should be Pending

### PR DESCRIPTION
**Pull request by KarinG**
Overview
----------------------------------------
Adding to our FunctionalJavascript testing

Before
----------------------------------------
No test for ACHEFT + Contribution status was incorrectly set to Completed

After
----------------------------------------
This PR adds a test for iATS Payments ACHEFT + Contribution status now correctly set to Pending

Technical Details
----------------------------------------
iATS Legacy Payment Processor

Comments
----------------------------------------

The test initially failed. But all good now.

Native Contribution pages -> also correctly put status = Pending (Incomplete) for ACHEFT.

Initial result before this PR:

```
1) Drupal\Tests\webform_civicrm\FunctionalJavascript\ContributionIatsTest::testSubmitACHEFTContribution
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'Pending'
+'Completed'
```

### CODE REVIEW

**Comment by mattwire** [comment]
@KarinG We can look at this tomorrow - it is a bug in webform_civicrm that will be fixed by https://github.com/colemanw/webform_civicrm/pull/691/files#diff-29604b8d3d680574d348a450de44692476847958c077b350b4dd553c4864f07dR740

**Comment by KarinG** [comment]
Thank you! @mattwire 

Cc: @adixon -> I'm going to try and edit webform civicrm - the trouble seems to be that it just assumes the ACHEFT is completed 🙂

**Comment by adixon** [comment]
Assumptions about the status of contributions have a long and painful history, and-no-doubt-future.

Originally, everything was assumed to be completed for one-time and pending until otherwise completed for recurring. I think there are still some credit-card centric bits of code kicking around, where it's assumed that a transaction is the same as a contribution is either a yes or no.

iATS still includes a few bits of override to try and make sure core doesn't mess things up.

**Comment by KarinG** [comment]
```
5.35.*
Error message Notice: Undefined index: line_item in CRM_Contribute_BAO_Contribution::checkTaxAmount()

/home/runner/work/webform_civicrm/webform_civicrm/tests/src/FunctionalJavascript/MembershipSubmissionTest.php:89

> 5.35.*
Error message Notice: Undefined index: invoice_id in Drupal\webform_civicrm\WebformCivicrmPostProcess->contributionRecur()

/home/runner/work/webform_civicrm/webform_civicrm/tests/src/FunctionalJavascript/MembershipSubmissionTest.php:89
```

**Comment by KarinG** [comment]
MembershipSubmissionTest uses dummy payment processor - so it should have a payment - I'll have to dig in!

**Comment by mattwire** [comment]
See https://github.com/colemanw/webform_civicrm/pull/698 to fix one of the PHP notices

**Comment by KarinG** [comment]
Rebased this after Matt's https://github.com/colemanw/webform_civicrm/pull/698

**Comment by KarinG** [comment]
Matt -> it will not pick up the latest head on a re-run. A re-run really is a re-run. I just pushed to this PR - that will force it to use the latest.

**Comment by KarinG** [comment]
Close! I don't want to remove support for 5.35.* yet (it still is the latest security update and stats.org shows lots of sites are using it) 

```
-> 1) Drupal\Tests\webform_civicrm\FunctionalJavascript\MembershipSubmissionTest::testSubmitMembershipAutoRenew
Error message Notice: Undefined index: line_item in CRM_Contribute_BAO_Contribution::checkTaxAmount()
```

Not sure why we're only getting this now - it must be related to the edits in this PR.

**Comment by KarinG** [comment]
The 1 of 8 tests that failed was the iATS cryptogram not loading (once). That's live testing. And ok ✅

**Comment by KarinG** [comment]
On merge -> 
image

**Pull request merged**
