### PR TITLE
Update for use of FormState.

### PR DESCRIPTION
**Pull request by puresyntax71**
Overview
----------------------------------------
Have an existing CiviCRM webform with a selected "Matching Rule" that is not provided by core. When you delete that "Matching Rule" in CiviCRM, there would be an error saying when you visit the CiviCRM settings page:

> Error: Cannot use object of type Drupal\Core\Form\FormState as array in Drupal\webform_civicrm\AdminForm->buildContactTab() (line 426 of /app/web/modules/contrib/webform_civicrm/src/AdminForm.php)

Before
----------------------------------------
Could not access CiviCRM settings.

After
----------------------------------------
Add fix.

Comments
----------------------------------------
Yeah, will try to add tests as well.

### CODE REVIEW

**Comment by KarinG** [comment]
Hi Arnold - thank you for this. The 5.35.* failure looks real. Re: test -> you can add to a test I recently added -> `ContactDedupeTest` - You could add a test in there that simulates this scenario - where you have a rule that no longer exists.

**Comment by puresyntax71** [comment]
Yeah, looks like the tests are failing although they seem to be unrelated to the changes from the PR.

**Comment by KarinG** [comment]
Tests on other repos failed last night as well - composer 2.3 just released.

**Comment by KarinG** [comment]
Yes - it's a composer issue. Constraining to `composer:2.2` works. I'll merge that shortly - then you can rebase your PR.

**Review by jitendrapurohit — APPROVED** [review]
Replicated the problem and confirmed that the changes here fixes the error. Merging.

**Pull request merged**
