### PR TITLE
Switch to api for fetching tags

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------------------------------------
Another BAO -> API conversion.

Before
----------------------------------------
Used BAO function to fetch tags.

After
----------------------------------------
Wrote our own function to get tags via api.

### CODE REVIEW

**Comment by colemanw** [comment]
@KarinG the simple way to test this PR is to create a bunch of nested tags and tagsets, then load the "CiviCRM" tab of a webform and inspect the tags and tagsets therein. It should look exactly the same before/after:

image

**Comment by KarinG** [comment]
Ok done! Tested:
image

**Comment by KarinG** [comment]
**PS** - Note: https://github.com/colemanw/webform_civicrm/blob/7.x-5.x/includes/utils.inc#L157 is incompatible with PHP 5.6

**Comment by colemanw** [comment]
@KarinG that's ok, CivICRM now requires PHP 7.

**Pull request merged**
