### PR TITLE
Revert "Use entity functions to save custom data"

### PR DESCRIPTION
**Pull request by colemanw**
Reverts #342 due to 2 problems discovered:

1. Custom data was [not being saved for any contact reference fields](https://www.drupal.org/project/webform_civicrm/issues/3171420).
2. Multi-record custom groups (e.g. the kind that displays as tabs on the contact summary screen) were not being saved.

### CODE REVIEW

**Comment by colemanw** [comment]
Because of the regressions, I'm reverting this and releasing 7.x-5.3 immediately. Hopefully @mattwire can fix the two bugs and then we can un-revert.

**Comment by ghost** [comment]
Just as well I checked this before installing 7.x-5.3.  The change in PR#342 is necessary for the recommended alternative solution to my PR#318 to work though fortunately I don't think we hit either of the cases mentioned above.  I see there is now a revised version of PR#342 - presumably this will be in a 7.x-5.4 release?

**Comment by colemanw** [comment]
@maynardsmith yes, #366 has been merged and will be part of 5.4 release. Should be out this week.

**Comment by Tekspertise** [comment]
The issue of 
Multi-record custom groups (e.g. the kind that displays as tabs on the contact summary screen) were not being saved.
appears to be still unresolved in 7.x-5.4
If more than one record is entered in the webform for the custom multiple record fieldset, these are all visible in the Webform results but only the first entry record is visible in Civi.
Have tested on 4 sites, all with 7.x-5.4, using different data types, all with same result

**Comment by pmosey** [comment]
Similar to Tekspertise and also on verison 7.x-5.4.
If two or more custom contact reference fields are changed in a webform. Only the first one appears to be saving in civi. I'll keep testing.

Created issue [here](https://www.drupal.org/project/webform_civicrm/issues/3196661).

**Pull request merged**
