### PR TITLE
Issue #2868220 - Webform not linking to CiviCRM when other language i…

### PR DESCRIPTION
**Pull request by francescbassas**
…s selected

### CODE REVIEW

**Comment by colemanw** [comment]
Thanks. Please use 2 spaces instead of tabs.

**Comment by francescbassas** [comment]
Done.

**Comment by colemanw** [comment]
I notice that there is no condition in here to check whether or not the node is a webform, and whether the `webform_civicrm` property exists in the source node.

**Comment by francescbassas** [comment]
Thanks, I commited your corrections.

**Comment by colemanw** [comment]
@francescbassas I've just pushed another change to try to make the conditions safer. Can you please test on your site and ensure it still works.

**Comment by francescbassas** [comment]
Thanks @colemanw. Tested and still working.

**Pull request merged**
