### PR TITLE
WIP - token fix - add screenshot

### PR DESCRIPTION
**Pull request by jitendrapurohit**

### CODE REVIEW

**Comment by jitendrapurohit** [comment]
looks like the ckeditor to add email content is missing -

email_handler

Works fine on local -

image

**Comment by KarinG** [comment]
Ok trying to figure this out now -> 6 days ago everything was fine. Now we don't have an editor. I'm going to look into the build differences:

image

**Comment by KarinG** [comment]
We are installing: webform dev:
drupal/webform (dev-6.x e9d4b54)

Interesting -> there is a commit to webform module (Dec08) - that involved CKEditor.

image

**Comment by KarinG** [comment]
I'm going to try and be specific -> latest release (instead of -dev)

**Comment by KarinG** [comment]
That was it! ✅

**Pull request closed without merging**
