### PR TITLE
Set case role (relationship) start date when creating case role, update existing active case role (relationship) if it already exists

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
Fix creating/updating case roles (relationships).

See related https://github.com/colemanw/webform_civicrm/pull/332

D7 or D8?
----------------------------------------
D8 (See #393 for D7).

Before
----------------------------------------
Error in relationship.create API call if a "duplicate" relationship exists (that could be active or inactive).

After
----------------------------------------
If an active relationship already exists with the same params update it (we probably don't actually need to update because I don't think there are any changes but this feels safest and means that hooks etc will continue to fire.

If an active relationship does not already exist (an inactive one might but we don't want to reactivate that because it preserves history) then we create a new relationship (case role) with the start_date set to today.

Previously we were not setting the start_date.

Technical Details
----------------------------------------
Check for existing relationships and add start_date to new ones.

Comments
----------------------------------------

### CODE REVIEW

**Comment by KarinG** [comment]
I've asked Olly (who I know uses case) to take a look at this PR.

**Comment by gibsonoliver** [comment]
Hi All

I can't see any issues with this idea.
As long as the start date on an existing active relationship isn't updated.

Olly

**Comment by mattwire** [comment]
@gibsonoliver That's correct, we only set start_date on new relationships

**Comment by KarinG** [comment]
👍 Thank you both! Merging.

**Pull request merged**
