### PR TITLE
Add Dedupe + Contact (Sub) Type Test

### PR DESCRIPTION
**Pull request by KarinG**
Overview
----------------------------------------
Adding first test for Dedupe Matching Rule testing!

Found and Fixed a bug in `contact_sub_type` Submissions while at it. Subsequent submission of webform adds another `contact_sub_type` of the same:
image

Before
----------------------------------------
No Dedupe Matching Rule or Contact Sub Type testing.

After
----------------------------------------
First Dedupe Matching or Contact Sub Type testing.

### CODE REVIEW

**Comment by KarinG** [comment]
Ok back to debugging the contact_sub_type issue -> having deja vu:

image

**Comment by KarinG** [comment]
@jitendrapurohit -> I fixed the 'double' `contact_sub_type` -> so that we don't end up with 'student' and 'Student' when merging array_keys:

`$params[$name] = array_unique(array_map("strtolower", array_merge($params[$name], $exist)));`

**Comment by KarinG** [comment]
We are ✅

**Comment by jitendrapurohit** [comment]
Replicated the problem and confirmed the fix 👍

**Pull request merged**
