### PR TITLE
Revert "Revert "Revert "Skip Stripe tests"""

### PR DESCRIPTION
**Pull request by KarinG**
Reverts colemanw/webform_civicrm#988

### CODE REVIEW

**Comment by mattwire** [comment]
@KarinG Seems to be complaining about conflicting artifacts

**Comment by KarinG** [comment]
Still trying to backtrack :-) Maybe too many tests running at the same time (they run on PR and merge). My tests (other PR) failed between PR and merge b/c the Stripe tests had been merged back in and failed. 

Let me know when you have a new release for Stripe. We are installing Stripe extension for WFC testing purposes to mimic end-to-end user testing.

**Comment by mattwire** [comment]
I've tagged https://lab.civicrm.org/extensions/stripe/-/releases/6.11.1

**Comment by KarinG** [comment]
Ok let's try this now.

**Pull request merged**
