### PR TITLE
Adding test for Custom Fields of type: Checkboxes.

### PR DESCRIPTION
**Pull request by KarinG**
Overview
----------------------------------------
Adding test for Custom Fields of type: Checkboxes.

Before
----------------------------------------
No such test

After
----------------------------------------

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by KarinG** [comment]
So can't find the Edit button for:

`Behat\Mink\Exception\ElementNotFoundException: Link with id|title|alt|text "edit-webform-ui-elements-civicrm-1-contact-1-cg1-custom-3-operations" not found.`

**Comment by KarinG** [comment]
We made it in the Build tab -> 
image

**Comment by KarinG** [comment]
Yes - that's the correct form -> and Listbox is checked by default (we may want to change that for Chekboxes and Radios) at some point.

**Comment by KarinG** [comment]
`Notice: Undefined index: #form_key in Drupal\webform_civicrm\Plugin\WebformElement\CivicrmOptions->getFieldOptions() (line 201 of /home/runner/work/webform_civicrm/webform_civicrm/src/Plugin/WebformElement/CivicrmOptions.php). `

**Comment by KarinG** [comment]
Oh and no Options -> need to check the API generation of the checkboxes!

**Comment by KarinG** [comment]
Still no checkbox Options! 🤔
image

**Comment by KarinG** [comment]
Ok - great 👍 - we now have checkboxes on the form -> 
image

We're hitting a webform notice here -> 
` Warning: Invalid argument supplied for foreach() in Drupal\Core\Render\Element\Checkboxes::valueCallback() (line 100 of core/lib/Drupal/Core/Render/Element/Checkboxes.php). `

Going to disable checking for notices for a minute here - but 👆 needs to be addressed too.

**Comment by KarinG** [comment]
Ok we're storing the checkbox values -> 
image

Now  onto making a readable Assert here...

**Comment by KarinG** [comment]
Ok ✅ now! 

But we still need to address:

`Warning: Invalid argument supplied for foreach() in Drupal\Core\Render\Element\Checkboxes::valueCallback() (line 100 of core/lib/Drupal/Core/Render/Element/Checkboxes.php).`

image

Here's native Drupal checkboxes -> 
image

**Comment by KarinG** [comment]
Uh one more notice ->

`Notice: Array to string conversion in Drupal\webform\WebformSubmissionStorage->saveData() (line 1343 of /Applications/MAMP/htdocs/d9civicrm.local/web/modules/contrib/webform/src/WebformSubmissionStorage.php) `

**Comment by KarinG** [comment]
image

**Comment by KarinG** [comment]
image

**Comment by KarinG** [comment]
Ok I did not solve all notices but solved some issues including the this one:
https://www.drupal.org/project/webform_civicrm/issues/3192043

**Comment by jitendrapurohit** [comment]
Not able to replicate the exact issue mentioned on https://www.drupal.org/project/webform_civicrm/issues/3192043, i.e, webform submission stores all the values even if one of the options is checked.

Was able to see the problem with missing checkboxes on the webform as mentioned by @KarinG in the above testing and confirm this PR change fixes the setting of form key and load the options on the form. Merging 👍

**Pull request merged**
