### PR TITLE
Expanding Activity Test

### PR DESCRIPTION
**Pull request by KarinG**
Overview/Summary:
----------------------------------------
**Added testing for:**
Activity Assignee
Retrieve and update existing activity using `cid1` and `aid` in the URL

**Fixed:**
Assignee field on config form

Before
----------------------------------------
Just testing Activity can be submitted and is stored properly in CiviCRM.

After
----------------------------------------
More testing and a bug fix! 🙂

### CODE REVIEW

**Comment by KarinG** [comment]
In the process -> found this notice after webform submission. This is the 'error' message I had run into previously:

```
// ToDo -> figure out what Error message it is! The submission itself works well.
// $this->assertPageNoErrorMessages();
$this->assertSession()->pageTextContains('New submission added to CiviCRM Webform Test.');
```

`Notice: Array to string conversion in Drupal\webform\WebformSubmissionStorage->saveData() (line 1339 of modules/contrib/webform/src/WebformSubmissionStorage.php).`

That's in webform itself.
Opening an issue: https://www.drupal.org/project/webform/issues/3191088

**Comment by KarinG** [comment]
Ok this is the issue -> 

image

**Comment by KarinG** [comment]
Out of the box -> Activity section in: D8/9
image

Out of the box -> Activity section in D7:
image

**Comment by KarinG** [comment]
Ok that worked in that we're able to assign a specific contact.

ToDo: rework the fields for Activity Participants and/or Assign Activity - make them similar to D7.

**Comment by KarinG** [comment]
This is better:

image

But having two - None - options is ...

**Comment by KarinG** [comment]
Ok got the update activity testing working!

**Comment by jitendrapurohit** [comment]
Was able to replicate and confirm that the change here fixes the activity assign element on the webform. Thanks for the fix @KarinG and  👍  for the test.

**Pull request merged**
