### PR TITLE
Also show line_item for participant if registered for a free event.

### PR DESCRIPTION
**Pull request by KarinG**
I've had this in production/live for CiviCamp Calgary since back in January

image

### CODE REVIEW

**Comment by colemanw** [comment]
Does it work if *all* the selected events are free? Expected behavior would be to hide the payment processor fields in that case, and not fail validation for lack of payment.

**Comment by KarinG** [comment]
Yes that works -> your registration for CiviCamp Calgary was an example of that. You had two $0 lineItems - and registered successfully for both CiviCamp day ($49 -> discounted to $0 and Sprint $0);

**Comment by KarinG** [comment]
PS - poke Tim to register for CiviCamp Calgary -> and he can report back to us confirming the $0 lineItems worked just fine :-)

**Comment by totten** [comment]
I was able to register for CiviCamp Calgary with a code -- both line items were processed as `$0`, and no billing blocks were required.

**Comment by KarinG** [comment]
Awesome!

**Comment by KarinG** [comment]
For completeness: registrations processed properly: 
image

**Pull request merged**
