### PR TITLE
D8/9 - Allow -User Select- on Contribution Financial type field

### PR DESCRIPTION
**Pull request by jitendrapurohit**
Overview
----------------------------------------
Allow `-User Select-` on contribution financial type field.

Before
----------------------------------------
Admins need to set Financial Type on the settings form (Contribution Tab).

image

After
----------------------------------------
Can be set to `-User Select-` -

Screenshot 2022-04-30 at 8 33 52 PM

Comments
----------------------------------------
FYI @KarinG @MegaphoneJon

### CODE REVIEW

**Comment by MegaphoneJon** [comment]
Thanks @jitendrapurohit! Test fails seem to relate.

**Comment by KarinG** [comment]
Passing now. Can you please review/test and give us an ok - then I'll merge it. Thanks Jon!

**Comment by MegaphoneJon** [comment]
My client gave this significant testing today and found no problems.  Thanks!

**Comment by KarinG** [comment]
Awesome - merging!

**Comment by KarinG** [comment]
I git pulled into an existing site -> and it flooded the dblog with: 

`CiviCRM_API3_Exception: Expected one FinancialType but found 0 in civicrm_api3() (line 134 of /var/www/drupal/vendor/civicrm/civicrm-core/api/api.php).`

'Fixed' -> by rolling back one commit. So... existing webforms appear to be quite upset about this commit.

**Comment by jitendrapurohit** [comment]
Should be fixed by https://github.com/colemanw/webform_civicrm/pull/741 @KarinG Can you pls confirm and merge?

Thanks.

**Pull request merged**
