### PR TITLE
Prevent creation of blank Billing Address or Billing Email

### PR DESCRIPTION
**Pull request by ghost**
Overview
----------------------------------------
Checks the content of a Billing Address and a Billing Email before creating them, and does not do so if they are empty.

D7 or D8?
----------------------------------------
This PR relates to D7WFC.  I have not looked at the equivalent for D8.

Before
----------------------------------------
The base Payment Processor creates a blank Billing Address, as do Immediate payment derivatives such as Cash or Cheque.  If no Email address is given (e.g. in an offline action by an administrator) there is also a blank Billing Email.  The recent provision by the Stripe PP for running without the Billing Address also creates a blank one.

After
----------------------------------------
Blank Billing Address and Email are not created.

### CODE REVIEW

**Comment by MegaphoneJon** [comment]
@maynardsmith If a contact doesn't already exist, then `$address['contact_id']` won't be defined.  So the `2` in `if (count(array_filter($address)) > 2) {` isn't going to fix the problem when a new contact is making a payment.

It's not pretty or clever, but `if ($address['street_address'] || $address['city'] || $address['country_id'] || $address['state_province_id'] || $address['postal_code']) {` is a more correct approach.

**Comment by ghost** [comment]
@MegaphoneJon  Ok, I'm quite happy with an alternative solution, especially if it plugs a hole.

**Comment by MegaphoneJon** [comment]
@maynardsmith to be clear - my PR isn't an alternative, it's a D8+ version.  I recommend you update yours to match, since I imagine the D8+ version will get looked at first, and if the code is basically identical this'll probably get merged at the same time.

Also if you make your change I'll vouch for the code as having been reviewed.

**Comment by ghost** [comment]
Belated Thanks.  We are actually running on D7 with a rule which tidies blank addresses up afterwards, so now there is a fix for D8 I am withdrawing this PR. as outdated.

**Pull request closed without merging**
