### PR TITLE
Edit max_instances for activities

### PR DESCRIPTION
**Pull request by mpaulso**
Increased number of activities from 60 to 65

D7 or D8?
----------------------------------------
D8

### CODE REVIEW

**Comment by colemanw** [comment]
Let's just make it `99` like other stuff in this module.

**Comment by KarinG** [comment]
99 sounds good! 😀

**Comment by colemanw** [comment]
@mpaulso can you squash your commits please?

**Comment by KarinG** [comment]
I can help you Mel! 

@colemanw - Melanie is just starting out with Github here. You may remember her from organizing CiviCamp Calgary with me :-)

**Comment by colemanw** [comment]
Ok cool. Welcome aboard Mel, thanks for the PR!

**Comment by mpaulso** [comment]
Thanks.

**Pull request merged**
