### PR TITLE
Use entity functions to save custom data

### PR DESCRIPTION
**Pull request by mattwire**
Overview
----------------------------------------
D8 port of https://github.com/colemanw/webform_civicrm/pull/342

Comments
----------------------------------------
Note I didn't test this on D8 yet.

### CODE REVIEW

**Comment by KarinG** [comment]
Thanks @mattwire 👍  

@jitendrapurohit - @colemanw checked the code and I ran a number of tests re: the D7 PR and merged it. If you could please review/test the D8 version that would be great - then we've collectively had a lot of eyes on it and that's good as custom fields are probably used by just about anyone using Webform CiviCRM module.

**Comment by jitendrapurohit** [comment]
seems like the multi select, checkbox and probably other fields involving multiple value submission fail after this change? @mattwire Can you pls confirm if you see the same behavior? I've tested on 2 sites with the same results.

**Comment by jitendrapurohit** [comment]
To replicate -

- Create a contact with a value on a checkbox custom field.
- Create a webform and include the same checkbox on it.
- Submit it for the contact.
- Note that the contact custom field value is removed after the above submission.

**Comment by KarinG** [comment]
@jitendrapurohit - thank you - I'm going back and add 'alphanumeric checkbox' to my D7 testing for this PR as well! Will circle back here.

**Comment by KarinG** [comment]
Ok - for the D7 version of this PR -> Checkboxes are working fine:

image

image

**Comment by mattwire** [comment]
@jitendrapurohit Are you saying you tested this on D8 and it's not working? It's working fine on D7 but I didn't actually test for D8.

**Comment by jitendrapurohit** [comment]
yes, this seems to be a d8-only problem.

**Comment by KarinG** [comment]
Ok looking at this PR (esp. checkboxes) now.

**Comment by KarinG** [comment]
`curl https://patch-diff.githubusercontent.com/raw/colemanw/webform_civicrm/pull/348.diff --output 348.diff
`
Ok - existing data -> in CiviCRM

image

**1. Before this PR** -> Going back to the webform -> the data load properly and any edits are saved properly.

```
root@52b4c507e3f3:/var/www/drupal/web/modules/contrib/webform_civicrm# cat 348.diff |patch -p1          
patching file includes/wf_crm_webform_base.inc
Hunk #1 succeeded at 659 (offset 3 lines).
patching file includes/wf_crm_webform_postprocess.inc
Hunk #5 succeeded at 1315 (offset 12 lines).
Hunk #6 succeeded at 1429 (offset 12 lines).
Hunk #7 succeeded at 1537 (offset 12 lines).
Hunk #8 succeeded at 2112 (offset 12 lines).
Hunk #9 succeeded at 2279 (offset 12 lines).
Hunk #10 succeeded at 2315 (offset 12 lines).
Hunk #11 succeeded at 2385 (offset 12 lines).
```

**2. With this PR** -> the webform -> the data load properly and any edits are saved properly.

**Here's the YAML of our test form:**
```
civicrm_1_contact_1_cg1_fieldset:
  '#type': fieldset
  '#title': 'Radio and Checkbox'
  '#form_key': civicrm_1_contact_1_cg1_fieldset
  civicrm_1_contact_1_cg1_custom_1:
    '#type': civicrm_options
    '#title': Radio
    '#options':
      1: 'Yes'
      0: 'No'
    '#format_items': ul
    '#format_items_html': ''
    '#format_items_text': ''
    '#form_key': civicrm_1_contact_1_cg1_custom_1
    '#parent': civicrm_1_contact_1_cg1_fieldset
    '#default_option': false
    '#default_value': false
  civicrm_1_contact_1_cg1_custom_2:
    '#type': civicrm_options
    '#title': Checkbox
    '#options':
      1: 'Check one'
      2: 'Check two'
    '#format_items': ul
    '#format_items_html': ''
    '#format_items_text': ''
    '#extra':
      aslist: 0
      multiple: 1
    '#form_key': civicrm_1_contact_1_cg1_custom_2
    '#parent': civicrm_1_contact_1_cg1_fieldset
    '#default_option': false
    '#default_value': false
  civicrm_1_contact_1_cg1_custom_3:
    '#type': civicrm_options
    '#title': 'Also radios'
    '#options':
      1: 'Yes also'
      2: 'No also'
    '#format_items': ul
    '#format_items_html': ''
    '#format_items_text': ''
    '#form_key': civicrm_1_contact_1_cg1_custom_3
    '#parent': civicrm_1_contact_1_cg1_fieldset
    '#default_option': false
    '#default_value': false

```

**Comment by KarinG** [comment]
@jitendrapurohit - please see above - I can't reproduce the issue you're seeing. Let me know if you're spotting any different. For completeness - these are our custom fields (including both ways to do radio boxes)

image

**Comment by jitendrapurohit** [comment]
Hmm, thanks for testing @KarinG but i still get the error. 

The custom field values are stored correctly before this change. It is removed only after applying this PR followed by drush cr. 

I'll dig more into this and see which line is messing up with the webform setup i have.

**Comment by jitendrapurohit** [comment]
Hmm, Have added this to a fresh local build and tested the PR against all custom field types. The issue isn't replicating there and webformm submission displays the correct checkbox and radio field values on the contact.

Also applied this to a live site and confirmed the fix with a simple webform, so think all good for now. Merging. Thanks @KarinG @mattwire

**Comment by KarinG** [comment]
@jitendrapurohit - thank you for circling back to this!

**Pull request merged**
