### PR TITLE
Deal with composer

### PR DESCRIPTION
**Pull request by demeritcowboy**
Overview
----------------------------------------
1. Temporarily use drupal 9.4.x-dev until a proper release for https://www.drupal.org/project/drupal/issues/3255749 is available.
2. After drupal is installed, add some config to drupal's top level composer.json to allow civi plugins.

@stesi561

### CODE REVIEW

**Comment by stesi561** [comment]
Nice solution! Fingers Crossed for test passes.

**Comment by demeritcowboy** [comment]
5.49 is expected:
```
1) Drupal\Tests\webform_civicrm\FunctionalJavascript\CaseSubmissionTest::testCaseSubmissionWithNonAdminUser
Behat\Mink\Exception\ResponseTextException: The text "New submission added to CiviCRM Webform Test." was not found anywhere in the text of the current page.
/home/runner/drupal/vendor/behat/mink/src/WebAssert.php:811
/home/runner/drupal/vendor/behat/mink/src/WebAssert.php:262
/home/runner/drupal/web/core/tests/Drupal/Tests/WebAssert.php:898
/home/runner/work/webform_civicrm/webform_civicrm/tests/src/FunctionalJavascript/CaseSubmissionTest.php:97
/home/runner/work/webform_civicrm/webform_civicrm/tests/src/FunctionalJavascript/CaseSubmissionTest.php:76
```

5.50 I'm not sure about:
```
1) Drupal\Tests\webform_civicrm\FunctionalJavascript\ContactSubmissionTest::testDraftSubmission
Behat\Mink\Exception\ElementNotFoundException: Button with id|name|title|alt|value "Save Draft" not found.
/home/runner/drupal/vendor/behat/mink/src/Element/TraversableElement.php:112
/home/runner/work/webform_civicrm/webform_civicrm/tests/src/FunctionalJavascript/ContactSubmissionTest.php:296
```

**Comment by demeritcowboy** [comment]
Seems like 5.50 was some weird temporary glitch. Passing 5.50 now.

**Comment by stesi561** [comment]
I think this is good to merge then - we just need to remember to revert off -dev once https://www.drupal.org/project/drupal/issues/3255749 is available in a released version.

**Comment by demeritcowboy** [comment]
Yes. At some point will want to move 5.45 to the new 5.51 ESR, and also will want to update to test 5.52 too, so it should come up soon enough that this will get updated.

**Pull request merged**
