### PR TITLE
Revert "Skip Stripe tests"

### PR DESCRIPTION
**Pull request by KarinG**
Reverts colemanw/webform_civicrm#940

### CODE REVIEW

**Comment by mattwire** [comment]
See https://lab.civicrm.org/extensions/stripe/-/commit/0753e8640db342d504eebfacf4eb3e81bba7cd18

**Comment by KarinG** [comment]
Tests pending

**Comment by KarinG** [comment]
Stripe test is still failing - WebDriver\Exception\UnexpectedAlertOpen: unexpected alert open: {Alert text :  Expired API Key provided: pk_test_k2******************RaYh}

**Comment by mattwire** [comment]
So that's somehow trying to use the old code/keys before the above commit!

**Comment by KarinG** [comment]
Is the above commit in a release yet?

**Comment by KarinG** [comment]
Actually - (and possibly) also it's testing against the Drupal/CiviCRM versions at the time of this original revert. So instead of reverting we need a new PR to test against the current D10.1.*, D10.2.* and D10.3.* (i.e. D11).

**Pull request merged**
