### PR TITLE
D10 - Replace jquery.once with new once API

### PR DESCRIPTION
**Pull request by jitendrapurohit**
Overview
----------------------------------------
https://www.drupal.org/node/3158256

Before
----------------------------------------
Deprecated usage of jquery.once. CiviCRM settings page does not load -

webform_civicrm_error

After
----------------------------------------
Replaced with core/once. CiviCRM settings page loads fine -

image

Technical Details
----------------------------------------
Follows the similar approach done in core webform module - https://www.drupal.org/project/webform/issues/3295609

Comments
----------------------------------------
@KarinG @demeritcowboy

### CODE REVIEW

**Comment by KarinG** [comment]
cc: @demeritcowboy - follow up PR re: D10 readiness! 

I think we (only) have one test failure -> 

There was 1 error:
1) Drupal\Tests\webform_civicrm\FunctionalJavascript\ContributionDummyTest::testCurrentEmployer
Behat\Mink\Exception\ElementNotFoundException: Select option with value|text "Default Organization" not found.

**Comment by KarinG** [comment]
Hi @jitendrapurohit - do you know why the order of the arguments changed?

e.g.

```
var wfCiviContact = (function ($, D) {
var wfCiviContact = (function (D, $, once) {
```

**Comment by jitendrapurohit** [comment]
@KarinG Ah, I just followed the before/after code changes from https://www.drupal.org/node/3158256, but don't really think it matters since its just used to wrap the function in a closure.

**Comment by KarinG** [comment]
Ah ok I see. I've pushed a trivial commit to re-run the tests.

**Comment by KarinG** [comment]
All green - merging 🎉

**Pull request merged**
