### PR TITLE
Fix relationship if multiple contact elements are included in the form

### PR DESCRIPTION
**Pull request by jitendrapurohit**
Overview
----------------------------------------
Fix relationship if multiple contact elements are included in the form

Before
----------------------------------------
- Multiple contact elements do not work on d8 webforms. I've added 2 contact existing field on the below webform, but only first contact element is loaded.

image

- Relationships are not populated in the edit element form.

image

- If second contact element form is edited and saved, it gets stored as "Generic Element"

image

After
----------------------------------------
- Relationships are correctly displayed.

image

- All contact elements on the webform are loaded.

image

Comments
----------------------------------------
@KarinG Sharing my inprogress work (in case you need). The remaining fix needed here is to populate the second contact element with the correct related cid.

### CODE REVIEW

**Comment by KarinG** [comment]
Awesome! Thank you - exciting.

**Comment by jitendrapurohit** [comment]
Just pushed a fix that takes care of loading the relationships too. 

image

**Comment by KarinG** [comment]
I'm in back to back meetings today through 8pm - but will promise to try/confirm first tomorrow morning.

**Comment by jitendrapurohit** [comment]
Sure, this is pending initial review from my end too. So keeping wip in the title for now.

Thanks :)

**Comment by KarinG** [comment]
Ok looking now!

Made a Contact in CiviCRM -> added Relationship Child of Parent (myself);

Logged in as myself:
 
image

Config for Parent: Default Value -> Set Default contact from: 
Current User

Config for Child:
image

Works!
image

Thank you for working on this @jitendrapurohit 
When you confirm it passes testing on your end as well - I'll merge it.

**Comment by jitendrapurohit** [comment]
Thanks @KarinG There are still some fixes needed on contact element form regarding populating filter options when > 2 contacts elements are present, filter section missing, etc. But I think I can create a new PR for that. 

This PR fixes the loading of multiple contact elements on the webform main page and assigning default cid on it. I'll keep it as it is and create a new PR for more fixes related to contact component.

As it passes manual testing of what it provides and does not break anything else on the form, can you pls merge this as this is better in that out?

Thanks.

**Comment by KarinG** [comment]
I completely agree 😀

**Pull request merged**
