### PR TITLE
Add ability to create new case based on existing case

### PR DESCRIPTION
**Pull request by colemanw**
Ports ##234 to the 8.x branch

### CODE REVIEW

**Comment by KarinG** [comment]
@bmango -> could you please test to see if this port of your PR works okie dokie on 8.x?

**Comment by bmango** [comment]
I am testing now but am getting an error on submit and white screen:

`Error: Call to undefined function user_is_logged_in() in /.../modules/contrib/webform_civicrm/includes/wf_crm_webform_postprocess.inc on line 1315`

Though I don't think this is related to this PR (this was in the apache log)

**Comment by KarinG** [comment]
Are you using -alpha2?

**Comment by bmango** [comment]
I ran `composer remove drupal/webform_civicrm` and then `composer require 'drupal/webform_civicrm:^5.0'`, then re-ran the form and everything is working on submit.

Can you confirm the patch for me to apply? Can I use https://patch-diff.githubusercontent.com/raw/colemanw/webform_civicrm/pull/250.patch? This is the one I had applied.

**Comment by KarinG** [comment]
Yes - it's this PR (#250) I usually grab the diff -> https://patch-diff.githubusercontent.com/raw/colemanw/webform_civicrm/pull/250.diff

**Comment by bmango** [comment]
Ok, I have double checked. Before applying the patch everything works fine. After applying the patch I get the same error. I get a white screen with _"The website encountered an unexpected error. Please try again later."_  And in the Apache log I have:

`Call to undefined function user_is_logged_in() in /home/.../dir/html/modules/contrib/webform_civicrm/includes/wf_crm_webform_postprocess.inc on line 1315`

I can give you the full error output if that is helpful.

**Comment by bmango** [comment]
As a quick reference I have uploaded the patched files to https://github.com/bmango/Test-Webform-Civicrm-PR-250

**Comment by KarinG** [comment]
Thanks @bmango - I'll circle back to this later today to see if I can reproduce what you're seeing.

**Comment by KarinG** [comment]
ah - right. That's a D7 leftover.

Try replace 
`user_is_logged_in()` 

with: 
`\Drupal::currentUser()->isAuthenticated()`

If that works -> add it to your patched repo and then create a new pull request.

**Comment by bmango** [comment]
Thanks for the help. I have updated the repository I created at https://github.com/bmango/Test-Webform-Civicrm-PR-250. 

I can't seem to create a new pull request where the base is 8.x-5.x compared to newCase as it just seems to re-direct me to this PR #250. Not sure if I am doing something wrong.

**Comment by KarinG** [comment]
It looks like your repo was not forked?
You can't open a pull request without forking the original project.
This is a good write up -> https://opensource.com/article/19/7/create-pull-request-github

If you want I can add this in but you're really close to getting your first PR into D8WFC :-)

**Comment by bmango** [comment]
Thanks very much for the resource for creating pull requests, that was very helpful. I think I have managed it... :)

**Comment by KarinG** [comment]
Excellent -> closing this one in favour of -> https://github.com/colemanw/webform_civicrm/pull/307

**Pull request closed without merging**
