### PR TITLE
Add contact labels when registering multiple participants

### PR DESCRIPTION
**Pull request by jitendrapurohit**
Registering more than 1 participant through webform gives a list of event on the confirmation page. This PR adds information of which participant is chosen for a specific event on confirmation as well as line items shown on view contribution page.

image

image

### CODE REVIEW

**Comment by KarinG** [comment]
Hi @jitendrapurohit - Pete showed me this a few weeks back - thank you for PRing it; is your client on 4.7 or 4.6? Coleman and I decided not to branch webform_civicrm module - so we're looking to make sure we continue to cover both;

**Comment by KarinG** [comment]
Doing some live testing on a 4.6 now;

**Comment by KarinG** [comment]
Before:
image

Participant Registrations: 
image

Contribution Record: 
image

**Comment by KarinG** [comment]
After: note: I'm getting the Fieldset labels -> not the Swimmer (which is an Existing Contact - Static - Relationship to Parent/Guardian); 

image

image

**Comment by KarinG** [comment]
After: CiviCRM Participant Registration (same as Before);
Contribution: not getting the lineItems:

image

**Comment by KarinG** [comment]
To summarize:

- great idea/improvement
- does not yet work for Existing Contacts though (on 4.6)
- don't get the lineItems (on 4.6)

Something related that has always bugged me is - when you view a single Participant record - it looks like there has been an overpayment:

image

**Comment by jitendrapurohit** [comment]
Hi @KarinG Thanks for the testing. Almost all of our clients are on 4.7, so I made this PR while working on the latest version of CiviCRM. I'll check with 4.6 and see if I can make this PR work on both the versions.

**Comment by KarinG** [comment]
Hi @jitendrapurohit - if it at least does not break anything in 4.6 [I did not see any fatal errors; perhaps you can double check/check for notices] - then I'm ok to merge this in. Our main goal is to not break anything in 4.6 [without fair warning to people]; But no need to support all new functionality in 4.6

**Comment by jitendrapurohit** [comment]
@KarinG I had a look at this and have updated the PR with the existing contact fix. The line items not shown on 4.6 is the default behaviour and doesn't seem to be related to this changes.

**Comment by KarinG** [comment]
Hi @jitendrapurohit - sorry for the delay on this. I've now upgraded my CiviCRM test site to 4.7 - and am applying your PR - getting the following error - which I'm pretty sure is unrelated to your PR - but it's very annoying. Can you still pay with credit cards via webform civicrm w/ 4.7.27?

image

**Comment by KarinG** [comment]
I don't think new functionality needs to work on 4.6 - we just need to be cautious not to break anything - and I've confirmed this PR does not. So I've merged it.

**Pull request merged**
