### PR TITLE
D8/9 - Multi-record custom fields are recorded twice when contributions are enabled

### PR DESCRIPTION
**Pull request by jitendrapurohit**
Overview
----------------------------------------
Fix duplicate multivalue records for billing contact

Before
----------------------------------------
Duplicate multi-value records are created for billing contact.

After
----------------------------------------
No duplicates created.

Comments
----------------------------------------
Fixes https://www.drupal.org/project/webform_civicrm/issues/3214105.

### CODE REVIEW

**Comment by jitendrapurohit** [comment]
The test added in this PR confirms the fix done for this issue + the issue raised on https://github.com/colemanw/webform_civicrm/pull/541. It'll fail the build until the related PRs are merged.

**Comment by jitendrapurohit** [comment]
The test commit also fixes the notice error logged with select contact widget -

image

**Comment by KarinG** [comment]
Now that we've addressed the issues with chromedriver 91 -> re-running these tests.

**Comment by KarinG** [comment]
I need to add a commit - otherwise it really just re-runs.

**Comment by KarinG** [comment]
Resolved conflict in `WebformCivicrmTestBase.php` - now we're running!

**Comment by KarinG** [comment]
Network error - could not download CiviCRM 5.35 -> will re-run again shortly.

**Comment by KarinG** [comment]
Ok two real errors -> 

```
1) Drupal\Tests\webform_civicrm\FunctionalJavascript\MultiCustomFieldsSubmissionTest::testAnonymousSubmitWithContribution
Behat\Mink\Exception\ResponseTextException: The text "New submission added to CiviCRM Webform Test." was not found anywhere in the text of the current page.

/home/runner/drupal/vendor/behat/mink/src/WebAssert.php:785
/home/runner/drupal/vendor/behat/mink/src/WebAssert.php:262
/home/runner/work/webform_civicrm/webform_civicrm/tests/src/FunctionalJavascript/MultiCustomFieldsSubmissionTest.php:148

--

There was 1 failure:

1) Drupal\Tests\webform_civicrm\FunctionalJavascript\MultiCustomFieldsSubmissionTest::testSubmitWebform
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'AprilEdited'
+'AprilAprilEdited'
```

**Comment by KarinG** [comment]
Ok one more issue:

```
1) Drupal\Tests\webform_civicrm\FunctionalJavascript\MultiCustomFieldsSubmissionTest::testAnonymousSubmitWithContribution
Behat\Mink\Exception\ResponseTextException: The text "New submission added to CiviCRM Webform Test." was not found anywhere in the text of the current page.
```

Let's reproduce that on my local first - and there it is:

image

Ok digging in.

**Comment by KarinG** [comment]
Ah -> screenshot to the rescue -> Billing Fields are required! This is `phpunit_browser_output%20(79)/Drupal_Tests_webform_civicrm_FunctionalJavascript_MultiCustomFieldsSubmissionTest-12-26186828.html`

image

**Comment by KarinG** [comment]
We are ✅ 🎉 - leaving it for you to hit the squash & merge button @jitendrapurohit

**Comment by jitendrapurohit** [comment]
Good to see this "all clear" ✅ . Merging. Thanks @KarinG 👍

**Pull request merged**
