### PR TITLE
Remove D10.1 from the test Matrix [EOL was June 2024]

### PR DESCRIPTION
**Pull request by KarinG**
See Title!

### CODE REVIEW

**Comment by demeritcowboy** [comment]
Suggestion: Change the 5.79.x-dev to 5.80.x-dev and replacing the one being removed with a 5.79.*

**Comment by KarinG** [comment]
Am I one version behind again already? :-)

**Comment by KarinG** [comment]
But we don't need D10.1 anymore. Now that we have D10.3 working again - next one up would be D11.

```
        include:
          - drupal: '10.2.*'
            civicrm: '5.78.*' -> latest security release
            php: '8.2'
          - drupal: '10.2.*'
            civicrm: '5.79.*' -> latest release
            php: '8.2'
          - drupal: '10.2.*'
            civicrm: '5.80.x-dev' -> RC
            php: '8.2'
          - drupal: '10.3.*'
            civicrm: 'dev-master' -> on the edge
            php: '8.3'
```

**Comment by demeritcowboy** [comment]
Yeah somebody keeps changing the numbers.

Last I checked 11 was still waiting on the parent webform. We could see where that's at.

**Pull request merged**
