### PR TITLE
D8/9 - Load state and county as civicrm options instead of textfield

### PR DESCRIPTION
**Pull request by jitendrapurohit**
Overview
----------------------------------------
Related Drupal Ticket - https://www.drupal.org/project/webform_civicrm/issues/3282579

I wonder if we should default the type of `state_province` element to `select` instead of `textfield`. It looks like the current status is 
- we load the state element as textfield
- change it to select using JS
- populate options in it dynamically based on country selection.

Wondering if we can merge 1 & 2 from the above steps? i.e, load the state field as select and use the JS just to populate the options. 

Before
----------------------------------------
State and county field are set to textfield by default. Element conditions using states API does not work.

After
----------------------------------------
State and County field are set to load as `select` type. States API works.

### CODE REVIEW

**Comment by jitendrapurohit** [comment]
FYI: @KarinG @junglebird

**Comment by jitendrapurohit** [comment]
Ah, Adding WIP again. I think this might need an upgrade step to ensure old webforms configured with text state fields work without any issues.

**Comment by KarinG** [comment]
@MegaphoneJon - Hi Jon - I'd really appreciate your eyes on this one before I hit merge.

**Comment by KarinG** [comment]
Ok testing this now!

**Comment by KarinG** [comment]
Ok I will need to circle back to this. I need to take a closer look to check why the PR does not appear to apply cleanly on this (live) site -> 

```
root@a1cd4e509a86:/var/www/drupal/web/sites/default/modules/webform_civicrm# git pull origin 
Already up to date.
root@a1cd4e509a86:/var/www/drupal/web/sites/default/modules/webform_civicrm# curl https://patch-diff.githubusercontent.com/raw/colemanw/webform_civicrm/pull/764.diff --output 764.diff
root@a1cd4e509a86:/var/www/drupal/web/sites/default/modules/webform_civicrm# git apply 764.diff 
error: patch failed: tests/src/FunctionalJavascript/LocationTypeTest.php:69
error: tests/src/FunctionalJavascript/LocationTypeTest.php: patch does not apply
```

@MegaphoneJon - did you have a chance to test/look at this PR? I want to try and get this merged

**Comment by MegaphoneJon** [comment]
Hi @KarinG I can look at this soon - but also Upperholme submitted the bug report and can possibly chime in.

**Comment by KarinG** [comment]
Sorry this took so long to review @jitendrapurohit

patch does not apply anymore -> 

```
karins-MBP:webform_civicrm sysadmin$ git apply 764.diff
error: patch failed: tests/src/FunctionalJavascript/LocationTypeTest.php:69
error: tests/src/FunctionalJavascript/LocationTypeTest.php: patch does not apply
```

**Comment by jitendrapurohit** [comment]
I've rebased it. Can you please try now @KarinG. Thanks.

**Comment by KarinG** [comment]
Ok great - patch applies cleanly.

sudo -u www-data drush updatedb
>  [notice] Update started: webform_civicrm_update_8004
>  [notice] Update completed: webform_civicrm_update_8004
 [success] Finished performing updates.

Created a new webform -> Options don't look good -> 

image

**Comment by jitendrapurohit** [comment]
@KarinG That is an expected behaviour since we load options in the state field dynamically based on Country selection.
 
I agree it looks odd on the Edit form. Maybe, it would be better to add some help text instead of just `Nothing`?

**Comment by KarinG** [comment]
Yes - it needs some help/explanation. 

Also when I was testing this (logged in user) my billing address would fill in except for State/Province field. One should not have to reselect it (PS I don’t think this was ever working).

**Comment by jitendrapurohit** [comment]
Updated the text so it displays like the following -

image

**Comment by jitendrapurohit** [comment]
>Also when I was testing this (logged in user) my billing address would fill in except for State/Province field. One should not have to reselect it (PS I don’t think this was ever working).

I think this was working when i initially submitted this PR. Maybe it broke due to some latest changes to the state fields. Have updated the PR to ensure this is working. Can you please confirm as well?

UPDATE: I've extended a test to confirm address fields are populated correctly.

Thanks.

**Comment by KarinG** [comment]
Existing webforms ->

image

Even if I select State/Province -> and Submit -> and then go through the form again -> State/Province remains blank.

New webform ->

image

Billing address in CiviCRM does have -> AB

image

**Comment by KarinG** [comment]
PS -> before testing above I pulled in all 6.x updates -> I'm at:

```
commit 1f40f1b09746d40115313f6c7cd441884b8d76c0 (HEAD -> 6.x, origin/HEAD, origin/6.x)
Merge: 462aa24 620bc69
Author: KarinG <karin@semper-it.com>
Date:   Sat Dec 3 12:04:59 2022 -0700

    Merge pull request #809 from jitendrapurohit/eway_billing
    D9 - Fix ipn processor payment with billing fields
```

I also checked for db updates (no additional ones) and cleared cache. 

We can merge this now and address the default on load later - if you prefer. As I mentioned before I don't recall this has been working.

**Comment by KarinG** [comment]
Ah and more concerning -> I can not get to Results on an existing webform anymore:

image

**Comment by KarinG** [comment]
One of these for every Result on that specific webform:

image

**Comment by jitendrapurohit** [comment]
@KarinG The default load on state field should be fixed now. Thanks for raising it again.

But, I can't replicate the issue on the Results page for the existing webforms. They seem to load fine for me. And I dont see any issues in logs for every submission. Can you please share the yaml of the affected webform so I can dig more?

Thanks.

**Comment by KarinG** [comment]
Thank you Jitendra - I've given you access to webform-civicrm.io ->

**Comment by KarinG** [comment]
Great - re-tested and able to view Results again for webforms with previous submissions.
Merging!

**Pull request merged**
