### PR TITLE
Allow change label from field image_url

### PR DESCRIPTION
**Pull request by rubofvil**
Overview
----------------------------------------

Allow change label the of the contact_image_url

Ref -> [Drupal Issue](https://www.drupal.org/project/webform_civicrm/issues/3257325)

Before
----------------------------------------

Error not allowing the format of the key when is saving the component image_url, because "image_URL" contains Uppercase

image

After
----------------------------------------

Allow change name of the label

image

Technical Details
----------------------------------------

Comments
----------------------------------------

### CODE REVIEW

**Comment by KarinG** [comment]
Thank you for the PR - I’ve added you to the list of users who can kick off tests. They are running now.

**Comment by petednz** [comment]
This looks like it is related to https://www.drupal.org/project/webform_civicrm/issues/3257325

**Comment by KarinG** [comment]
@jitendrapurohit - could you please review this PR? Tests are all ✅ 🎉

**Comment by jitendrapurohit** [comment]
Tested. Thanks for the PR @rubofvil

**Pull request merged**
