### PR TITLE
Allow processor to determine whether email address is required

### PR DESCRIPTION
**Pull request by aydun**
See https://lab.civicrm.org/dev/core/issues/1584

### CODE REVIEW

**Comment by colemanw** [comment]
+1 This looks safe and backward-compatible. however it should not be merged until the core issue is resolved.

**Comment by aydun** [comment]
@colemanw - fyi, core PR has been merged:  https://lab.civicrm.org/dev/core/-/commit/93f55ad6949e09c77ad8ecf9e2e100a70e0f33fd  Can this be merged now?

**Comment by colemanw** [comment]
Yep, looks good!

**Comment by aydun** [comment]
Thanks!

**Comment by colemanw** [comment]
@KarinG I cherry-picked this into 8.x

**Pull request merged**
